name: Validate-turtle

# Controls when the action will run. 
on:
  workflow_dispatch:
  
  pull_request:
    branches:
    - develop
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install tools
        run: echo "test"
