name: validate turtle

# Controls when the action will run. 
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
    - develop
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    
      - name: Cache Raptor
        uses: actions/cache@v2
        id: cache-raptor2-utils
        with:
            path: "~/raptor2-utils"
            key: ${{secrets.RAPTOR2_UTILS_VERSION}}
    
    
      - name: Install valgrind
        env:
          CACHE_HIT: ${{steps.cache-raptor2-utils.outputs.cache-hit}}
          RAPTOR2_UTILS_VERSION: ${{secrets.RAPTOR2_UTILS_VERSION}}
        run: |
            if [[ "$CACHE_HIT" == 'true' ]]; then
              sudo cp --verbose --force --recursive ~/raptor2-utils/* /
            else
              sudo apt-get install --yes raptor2-utils="$RAPTOR2_UTILS_VERSION"
              mkdir -p ~/raptor2-utils
              sudo dpkg -L raptor2-utils | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/raptor2-utils/
            fi
            
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate ontology
        run: find -type f -name "*.ttl" -not -path "./.git/*" -not -path "./examples/contracts-and-usage-policy/*"| sed 's/.*/"&"/'  | xargs -n1 rapper -q -i turtle > /dev/null
