# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout to branch
        uses: actions/checkout@v2
      
      - working-directory: ./
      
      - name: Install tools
        run: sudo apt-get install raptor2-utils

      - name: Validate Turtle files
        run: find -type f -name "*.ttl" -not -path "./.git/*" -not -path "./examples/contracts-and-usage-policy/*" | sed 's/.*/"&"/' |xargs -n1 rapper -q -i turtle > /dev/null

