name: validate turtle

# Controls when the action will run. 
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
    - develop
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: install
        run: sudo apt-get install raptor2-utils
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate ontology
        run: find -type f -name "*.ttl" -not -path "./.git/*" -not -path "./examples/contracts-and-usage-policy/*"| sed 's/.*/"&"/'  | xargs -n1 rapper -q -i turtle > /dev/null
